config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'page/index'
  post 'page/broadcast'

  resources :users, only: [:index]
  resources :private_conversations, only: [:new, :create]
  resources :conversations, only: [:index, :show]

  root 'users#index'
  #root 'devise/registrations#new'
  #root 'devise/sessions#destroy' 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/concerns/emojify.rb
module Emojify
  def self.emojify(content)
    content.to_str.gsub(/:([\w+-]+):/) do |match|
      if emoji = Emoji.find_by_alias($1)
        %(<img alt="#$1" src="/images/emoji/#{emoji.image_filename}" style="vertical-align:middle"/>)
      else
        match
      end
    end.html_safe if content.present?
  end
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :receiver, class_name: 'User'
  has_many :private_conversations, -> { order(created_at: :asc)  }, dependent: :destroy
  validates :author, uniqueness: {scope: :receiver}

  scope :participating, -> (user) do
    where("(conversations.author_id = ? OR conversations.receiver_id = ?)", user.id, user.id)
  end

  scope :between, -> (sender_id, receiver_id) do
    where(author_id: sender_id, receiver_id: receiver_id).or(where(author_id: receiver_id, receiver_id: sender_id))
  end

  def with(current_user)
    author == current_user ? receiver : author
  end

  def participates?(user)
    author == user || receiver == user
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
end

app/models/personal_message.rb
class PersonalMessage < ApplicationRecord
  belongs_to :conversation
  belongs_to :user
end

app/models/private_conversation.rb
class PrivateConversation < ApplicationRecord
  include Rails.application.routes.url_helpers
  belongs_to :conversation
  belongs_to :user
  has_one_attached :attachment

  def self.create(params, current_user, conversation)
    current_user.private_conversations.create!(params.merge({conversation: conversation}))
  end

  def notify(current_user)
    ActionCable.server.broadcast notifying_channel(current_user), message_hash(current_user)
  end

  def notifying_channel(current_user)
    notifying_person_id = (current_user.id == conversation.author_id) ? conversation.receiver_id : conversation.author_id 
    "notifications_#{notifying_person_id}_channel"
  end

  def message_hash(current_user)
    avatar_html = ""
    if current_user.avatar.attached?
      person = (user == current_user) ? "You" : user.full_name
      avatar_html = "<img src='" + rails_blob_path(current_user.avatar, only_path: true) + "' alt=" + person + " class='mr-3 mt-3 rounded-circle border border-dark' style='width:30px;'>"
    end

    attachment_html = ""
    if attachment.attached?
      attachment_html = "<div class='attachment'><image src='" + rails_blob_path(attachment, only_path: true) + "' style='width:80px;height:auto;'></div>"
    end

    { 
      message: Emojify::emojify(body),
      created_at: created_at.strftime("%F, %I:%M %p"),
      user: current_user.full_name,
      avatar: avatar_html,
      attachment: attachment_html
    }
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :authored_conversations, class_name: 'Conversation', foreign_key: 'author_id'
  has_many :received_conversations, class_name: 'Conversation', foreign_key: 'received_id'
  has_many :private_conversations, dependent: :destroy
  has_one_attached :avatar

  def full_name
    first_name.capitalize + " " + last_name.capitalize
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :emojify
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  private
  def configure_permitted_parameters
    added_attrs = [:first_name, :last_name, :email, :password, :password_confirmation, :avatar]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  def index
    @conversations = Conversation.participating(current_user).order('updated_at DESC')
    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    gon.current_user_id = current_user.id
    @conversation = Conversation.find_by(id: params[:id])
    @private_conversation = PrivateConversation.new
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
  end

  def broadcast
    ActionCable.server.broadcast 'web_notifications_channel', message: Emojify::emojify("#{params[:article][:body]}")
    return render nothing: true, status: 200
  end
end

app/controllers/personal_messages_controller.rb
class PersonalMessagesController < ApplicationController
  before_action :find_conversation!

  def new
    redirect_to conversation_path(@conversation) and return if @conversation
    @personal_message = current_user.personal_messages.build
  end

  def create
    @conversation ||= Conversation.create(author_id: current_user.id,
                                          receiver_id: @receiver.id)
    @personal_message = current_user.personal_messages.build(personal_message_params)
    @personal_message.conversation_id = @conversation.id
    @personal_message.save!

    flash[:success] = "Your message was sent!"
    redirect_to conversation_path(@conversation)
  end

  private

  def personal_message_params
    params.require(:personal_message).permit(:body)
  end

  def find_conversation!
    if params[:receiver_id]
      @receiver = User.find_by(id: params[:receiver_id])
      redirect_to(root_path) and return unless @receiver
      @conversation = Conversation.between(current_user.id, @receiver.id)[0]
    else
      @conversation = Conversation.find_by(id: params[:conversation_id])
      redirect_to(root_path) and return unless @conversation && @conversation.participates?(current_user)
    end
  end
end

app/controllers/private_conversations_controller.rb
class PrivateConversationsController < ApplicationController
  before_action :find_conversation!

  def new
    redirect_to conversation_path(@conversation) and return if @conversation
    @private_conversation = current_user.private_conversations.build
  end

  def create
    @conversation ||= Conversation.create(author_id: current_user.id, receiver_id: @receiver.id)
    @private_conversation = PrivateConversation.create(personal_message_params, current_user, @conversation)
    @private_conversation.notify(current_user)
    redirect_to conversation_path(@conversation)
  end

  private

  def personal_message_params
    params.require(:private_conversation).permit(:body, :attachment)
  end

  def find_conversation!
    if params[:receiver_id]
      @receiver = User.find_by(id: params[:receiver_id])
      redirect_to(root_path) and return unless @receiver
      @conversation = Conversation.between(current_user.id, @receiver.id)[0]
    else
      @conversation = Conversation.find_by(id: params[:conversation_id])
      redirect_to(root_path) and return unless @conversation && @conversation.participates?(current_user)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/common/_header.html.erb
<%= content_for :head do %>
  <%= stylesheet_link_tag 'header' %>
<% end %>

<div class="jumbotron">
  <div class="row">
    <div class="box-1 col-1">
      <%= link_to "Home", root_path, class: "link-to-text-color" %>
    </div>
    <div class="box-2 col"></div>
    <div>
      <% if current_user.avatar.attached? %>
        <span class="avatar">
          <image src="<%=(url_for(current_user.avatar))%>" class="rounded-circle border border-dark" style="width:30px">
        </span>
      <% end %>
      <span><strong><%= current_user.first_name.capitalize %> <%= current_user.last_name.capitalize %></strong></span>
      <span><%= link_to "Sign out", destroy_user_session_path, {method: :delete} %></span>
      <span><%= link_to "Edit", edit_user_registration_path(current_user)  %></span>
    </div>
  </div>
</div>

app/views/conversations/index.html.erb
<h1>Your conversations</h1>

<div id="conversations">
    <%= render @conversations %>
</div>

app/views/conversations/show.html.erb
<%= render "common/header" %>

<h3>Chatting with <%= @conversation.with(current_user).full_name %></h3>

<div id="conversation-main" style="overflow:scroll; height:350px;" >
  <div id="conversation-body" data-conversation-id="<%= @conversation.id %>">
    <%= render @conversation.private_conversations %>
  </div>
</div>

<%= form_for @private_conversation do |f| %>
  <%= hidden_field_tag 'conversation_id', @conversation.id %>
  <%= f.text_field :body, style: "width:100%;" %>
  <br>
  <%= f.file_field :attachment %>
  <br>
<% end %>

<script>
  $(document).ready(function(){
    var objDiv = document.getElementById("conversation-main");
    objDiv.scrollTop = objDiv.scrollHeight;
  })
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatRoom</title>
    <%= include_gon %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/page/broadcast.html.erb
<h1></h1>

app/views/page/index.html.erb
<%= render "common/header" %>

<h1>Chat Room</h1>

<h2>Broadcast Message</h2>
<form class="nifty_form" id="new_article" action="broadcast" accept-charset="UTF-8" method="post" data-remote="true">
  <input type="hidden" name="authenticity_token" value="NRkFyRWxdYNfUg7vYxLOp2SLf93lvnl+QwDWorR42Dp6yZXPhHEb6arhDOIWcqGit8jfnrPwL781/xlrzj63TA==" />
  <textarea name="article[body]" id="article_body" cols="60" rows="2"></textarea>
  <div>
    <input type="submit" name="commit" value="Send" data-disable-with="Create" />
  </div>
</form>
<div>
<h2>Received Messages</h2>
<div id="messages"></div>

app/views/private_conversations/_private_conversation.html.erb
<% conversation_user = private_conversation.user %>
<% person = (conversation_user == current_user) ? "You" : private_conversation.user.full_name %>

<div class="media border p-2">
  <img src="<%=(url_for(conversation_user.avatar))%>" alt=<%= person %> class="mr-3 mt-3 rounded-circle border border-dark" style="width:30px;">
  <div class="media-body">
    <h6><%= person %> <small><i>Posted on <%= private_conversation.created_at.strftime("%F, %I:%M %p") %>  </i></small></h6>
    <p><%= Emojify::emojify private_conversation.body %></p>
    <% if private_conversation.attachment.attached? %>
      <div class="attachment">
        <image src="<%=(url_for(private_conversation.attachment))%>" style="width:80px;height:auto;">
      </div>
    <% end %>
  </div>
</div>

app/views/private_conversations/new.html.erb
<%= include_gon %>
<%= render "common/header" %>
<h1>New message to <%= @receiver.email %></h1>

<%= form_for @private_conversation do |f| %>
  <%= hidden_field_tag 'receiver_id', @receiver.id %>
  <%= f.label :body %>
  <%= f.text_area :body %>
  <%= f.submit %>
<% end %>

app/views/users/_user.html.erb
<% if current_user.email != user.email %>
  <li>
    <%= user.email %> | <%= link_to 'chat', new_private_conversation_path(receiver_id: user) %>
  </li>
<% end%>

app/views/users/index.html.erb
<%= render "common/header" %>

<div class="row">
  <div class="col-2"></div>
  <div class="col-5">
    <h1>Rooms</h1>
    <ul>
      <li>Chat Room 1 | <%= link_to 'chat', page_index_path %></li>
    </ul>
    <h1>Users</h1>
    <ul><%= render @users %></ul>
  </div>
  <div class="col-5"></div>
</div>